#!/bin/sh
# Run one command against the Mesa 25.0.7 stack installed under /usr/local/ans.
set -e

export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/local/ans/share/glvnd/egl_vendor.d/50_mesa.json
export __GLX_VENDOR_LIBRARY_NAME=mesa
export LIBGL_DRIVERS_PATH=/usr/local/ans/lib/dri:/usr/lib/aarch64-linux-gnu/dri
export GBM_BACKENDS_PATH=/usr/local/ans/lib/gbm
# Some RK3588 BSP images put their proprietary Mali libEGL/libGLES ahead of
# Debian's GLVND dispatcher in ld.so.cache.  Keep the private Mesa libraries
# first, then select the distro GLVND client libraries explicitly.
GLVND_LIBDIR=/usr/lib/aarch64-linux-gnu
export LD_LIBRARY_PATH=/usr/local/ans/lib:${GLVND_LIBDIR}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

exec "$@"
